version: '3'

services:
  web:
    build: web/.
    volumes:
      - ./web/:/app
    links:
      - db
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - web/.env
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 30000:3306
    volumes:
      - ./db/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql

