apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
  labels:
{{ include "flaskapp.labels" . | indent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "flaskapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
