#!/usr/bin/env bash
eksctl create cluster \
--name prod \
--version 1.12 \
--nodegroup-name standard-workers \
--node-type t3.medium \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--node-ami auto \
--region us-east-1 \
--zones us-east-1a,us-east-1b,us-east-1d \
--ssh-access \
--ssh-public-key ekskey \
--storage-class=false
